  # environment variables
environment:
  path_to_sln: src\FileProviders.sln
skip_tags: true
install:
  - choco install gitversion.portable -pre -y
  - cinst gitlink -y -version 2.4.1
image: Visual Studio 2022 
assembly_info:
  patch: false
before_build:
- ps: gitversion /l console /output buildserver
- cmd: msbuild %path_to_sln% /t:restore /p:PackageVersion=%GitVersion_NuGetVersion%
build:
  project: '%path_to_sln%'
  verbosity: minimal
after_build:
- cmd: gitlink . -u https://github.com/%APPVEYOR_REPO_NAME% -b %APPVEYOR_REPO_BRANCH% -s %APPVEYOR_REPO_COMMIT% -f %path_to_sln%
- cmd: msbuild %path_to_sln% /t:Pack /p:PackageVersion=%GitVersion_NuGetVersion%
artifacts:
- path: /src/**/*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: FKbUAoq5UFzB6qmajL9N//y3XyBQ0nhPOjh26UteP5nLeGBLyLJaZ9udpKZRvspr
  skip_symbols: false
  artifact: /.*\.nupkg/